site_name: GP-ENGINE Documentation

repo_url: https://github.com/GreatPlainsNetwork/gp-engine-docs
edit_uri: edit/main/docs/
theme:
  name: material
  features:
    - content.action.edit


nav:
  - Home: index.md


markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html

