site_name: GP-ENGINE Documentation

repo_url: https://github.com/GreatPlainsNetwork/gp-engine-docs
edit_uri: edit/main/docs/
theme:
  name: material
  features:
    - content.action.edit
    - navigation.footer


nav:
  - Home: index.md
  - Node Configuration: node-configuration.md


markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html

extra:
  social:
    - icon: material/web
      link: https://gp-engine.org
      name: GP-Engine Website

copyright: This project is supported by National Science Foundation under Grant <a href="https://www.nsf.gov/awardsearch/showAward?AWD_ID=2322218" className="underline">OAC-2322218</a>. Any opinions, findings, conclusions or recommendations expressed in this material are those of the authors and do not necessarily reflect the views of the National Science Foundation.